# Generated by Django 2.2.6 on 2019-12-21 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=2)),
                ('hostel_gender', models.CharField(max_length=7)),
                ('hostel_course', models.CharField(max_length=3)),
                ('hostel_no_of_floor', models.IntegerField()),
                ('hostel_no_of_room', models.IntegerField()),
                ('rooms_type', models.CharField(default=None, max_length=1)),
                ('hostel_no_of_room_available', models.IntegerField()),
                ('hostel_warden', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('room_luxury', models.CharField(default=None, max_length=10)),
                ('is_room_vacant', models.IntegerField(default=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_allocation.HostelAllocation')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=10, null=True, unique=True)),
                ('student_name', models.CharField(max_length=200, null=True)),
                ('student_mobile', models.CharField(max_length=11)),
                ('student_gender', models.CharField(default=None, max_length=1, null=True)),
                ('student_gpa', models.FloatField()),
                ('student_course', models.CharField(default=None, max_length=8)),
                ('student_year', models.CharField(default=None, max_length=1, null=True)),
                ('physical_problem', models.BooleanField(default=False)),
                ('room_allotted', models.BooleanField(default=False)),
                ('student_room_no', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hostel_allocation.Room')),
            ],
        ),
    ]
